name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Upload to Azure Blob Storage
      run: |
        az storage blob upload-batch --destination '$web' --source client --connection-string "${{ secrets.AZURE_CONNECTION_STRING }}" --overwrite